services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - ./backend/.env
