services:
  frontend:
    build: ./frontend-services
    ports:
      - "3000:3000"
    depends_on:
      - signaling
      - auth
    networks:
      - videochat-network

  signaling:
    build: ./signalling-services
    ports:
      - "5001:5001"
    depends_on:
      - signaling-db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@signaling-db:5432/signalingdb
    networks:
      - videochat-network

  auth:
    build: ./auth-service
    ports:
      - "5002:5002"
    depends_on:
      - auth-db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@auth-db:5432/authdb
    networks:
      - videochat-network
  
  speech:
    build: ./speech-service
    ports:
      - "5003:5003"
    depends_on:
      - speech-db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@speech-db:5432/speechdb
      - ASSEMBLYAI_API_KEY= ${AssemblyAI_API_KEY}
      - OPENAI_API_KEY= ${OPENAI_API_KEY}
    volumes:
      - ./speech-service/model:/speech-service/model  
    networks:
      - videochat-network

  auth-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: authdb
    ports:
      - "5435:5432"
    networks:
      - videochat-network

  signaling-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: signalingdb
    ports:
      - "5433:5432"
    networks:
      - videochat-network

  speech-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: speechdb
    ports:
      - "5434:5432"
    networks:
      - videochat-network
  
networks:
  videochat-network:
    driver: bridge



